sonar.projectKey=j3vnloko_microservicio-devops
sonar.projectName=Microservicio DevOps - EP3
sonar.organization=j3vnloko

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml